<?php
// src/GlobalGenerator.php

namespace Eril\TblClass\Generators;

use Eril\TblClass\Config;
use PDO;

class GlobalGenerator extends Generator
{
    private array $foreignKeys = [];

    public function __construct(PDO $pdo, Config $config, bool $checkMode = false)
    {
        parent::__construct($pdo, $config, $checkMode, 'global');
        $this->mode = 'global';
    }

    protected function generateContent(array $tables, array $foreignKeys = [], ?string $schemaHash = null): string
    {
        $content = "<?php\n\n";
        $content .= $this->generateHeader($schemaHash);
        $content .= $this->generateGlobalConstants($tables);
        $content .= "\n" . $this->generateForeignKeyConstants($foreignKeys) . "\n";
        // copyright
        $content .= "\n# auto-generated by tbl-class v3.2 CLI:";
        $content .= "\n# php vendor/bin/tbl-class --global # ↻ regenerate";
        $content .= "\n# php vendor/bin/tbl-class --check  # ✓ check\n";

        return $content;
    }

    private function generateHeader(string $schemaHash): string
    {
        $header = "/**\n";
        $header .= " * Global database constants for schema '{$this->dbName}'\n";
        $header .= " * \n";
        $header .= " * @schema-hash md5:{$schemaHash}\n";
        $header .= " * @generated " . date('Y-m-d H:i:s') . "\n";
        $header .= " * @tool      tbl-class --global\n";
        $header .= " * \n";
        $header .= " * @warning AUTO-GENERATED - DO NOT EDIT MANUALLY\n";
        $header .= " */\n\n";

        return $header;
    }

    private function generateGlobalConstants(array $tables): string
    {
        $content = '';

        foreach ($tables as $table) {
            $columns = $this->getColumns($table);

            if (empty($columns)) {
                continue;
            }

            // Usa NamingResolver para obter o nome da constante da tabela
            $tableConst = $this->namingResolver->getTableConstName($table, $this->mode);
            $content .= "/** Table: $table */\n";
            $content .= "const {$tableConst} = '$table';\n";

            foreach ($columns as $column) {
                // Usa NamingResolver para obter o nome da constante da coluna
                $columnConst = $this->namingResolver->getColumnConstName($table, $column, $this->mode);
                $content .= "const {$columnConst} = '$column';\n";
            }

            $content .= "\n";
        }

        return $content;
    }

    private function generateForeignKeyConstants(array $foreignKeys): string
    {
        $content = '';

        if (empty($foreignKeys)) {
            $content .= "// No foreign keys found in the database\n";
            return $content;
        }

        $content .= "// --- Foreign Keys ---\n\n";
        foreach ($foreignKeys as $fk) {
            // Usa NamingResolver para obter o nome da constante FK
            $fkConst = $this->namingResolver->getForeignKeyConstName(
                $fk['from_table'],
                $fk['to_table'],
                $this->mode
            );
            $value = $fk['from_column'];

            $content .= "/** Foreign key: {$fk['from_table']}.{$fk['from_column']} → {$fk['to_table']}.{$fk['to_column']} */\n";
            $content .= "const {$fkConst} = '{$value}';\n";
        }

        return $content;
    }

    protected function showInstructions(): void
    {
        $outputFile = $this->config->getOutputFile($this->mode);
        $relativePath = str_replace(getcwd() . '/', '', $outputFile);

        echo "\n💡 To use these constants, add to composer.json:\n";
        echo "   \"autoload\": {\n";
        echo "       \"files\": [\"$relativePath\"]\n";
        echo "   }\n";
        echo "\n   Then run: composer dump-autoload\n";
        echo str_repeat('-', 50) . "\n";
    }
}
