<?php

namespace Eril\TblClass\Generators;

use Eril\TblClass\Config;
use Eril\TblClass\Schema\SchemaReaderInterface;
use Eril\TblClass\OutputWriter;

/**
 * Gera constantes globais para tabelas e colunas
 */
class GlobalGenerator extends Generator
{
    public function __construct(
        SchemaReaderInterface $schema,
        Config $config,
        bool $checkMode = false
    ) {
        parent::__construct($schema, $config, $checkMode, 'global');
    }

    /**
     * Gera o conteúdo completo do arquivo PHP
     */
    protected function generateContent(array $tables, array $foreignKeys = [], ?string $schemaHash = null): string
    {
        $content  = "<?php\n\n";
        $content .= $this->generateHeader($schemaHash);
        $content .= $this->generateGlobalConstants($tables);
        $content .= $this->generateForeignKeyConstants($foreignKeys);

        $content .= "\n# auto-generated by tbl-class v3.2 CLI:";
        $content .= "\n# php vendor/bin/tbl-class --global # ↻ regenerate";
        $content .= "\n# php vendor/bin/tbl-class --check  # ✓ check\n";

        return $content;
    }

    private function generateHeader(?string $schemaHash): string
    {
        $time = date('Y-m-d H:i:s');
        $dbName = $this->schema->getDatabaseName();

        return <<<PHP
/**
 * Global database constants for schema '{$dbName}'
 *
 * @schema-hash md5:{$schemaHash}
 * @generated   {$time}
 * @tool        tbl-class --global
 *
 * ⚠ AUTO-GENERATED - DO NOT EDIT MANUALLY
 */


PHP;
    }

    private function generateGlobalConstants(array $tables): string
    {
        $content = '';

        foreach ($tables as $table) {
            $columns = $this->schema->getColumns($table);
            if (empty($columns)) continue;

            $tableConst = $this->namingResolver->getTableConstName($table, $this->mode);
            $content .= "/** Table: $table */\n";
            $content .= "const {$tableConst} = '$table';\n";

            foreach ($columns as $column) {
                $columnConst = $this->namingResolver->getColumnConstName($table, $column);
                $content .= "const {$columnConst} = '$column';\n";
            }

            $content .= "\n";
        }

        return $content;
    }

    private function generateForeignKeyConstants(array $foreignKeys): string
    {
        if (empty($foreignKeys)) {
            return "// No foreign keys found in the database\n\n";
        }

        $content = "// --- Foreign Keys ---\n\n";

        foreach ($foreignKeys as $fk) {
            $fkConst = $this->namingResolver->getForeignKeyConstName(
                $fk['from_table'],
                $fk['to_table'],
                $this->mode
            );

            $content .= "/** Foreign key: {$fk['from_table']}.{$fk['from_column']} → {$fk['to_table']}.{$fk['to_column']} */\n";
            $content .= "const {$fkConst} = '{$fk['from_column']}';\n";
        }

        $content .= "\n";
        return $content;
    }

    /**
     * Mostra instruções de uso (autoload)
     */
    protected function showInstructions(): void
    {
        $outputFile = $this->config->getOutputFile($this->mode);
        $relativePath = str_replace(getcwd() . '/', '', $outputFile);

        echo "\n💡 To use these constants, add to composer.json:\n";
        echo "   \"autoload\": {\n";
        echo "       \"files\": [\"$relativePath\"]\n";
        echo "   }\n";
        echo "\n   Then run: composer dump-autoload\n";
        echo str_repeat('-', 50) . "\n";
    }
}
