<?php

namespace Eril\TblClass\Generators;

use Eril\TblClass\Traits\OnJoinGenerator;

/**
 * Gera a versão legacy (v3) das constantes de tabelas, colunas e FKs
 */
class LegacyGenerator extends Generator
{
    use OnJoinGenerator;

    /**
     * Gera todo o conteúdo do arquivo PHP
     */
    protected function generateContent(array $tables, array $foreignKeys = [], ?string $schemaHash = null): string
    {
        $namespace = $this->config->get('output.namespace');
        $aliases = [];
        $this->namingResolver->reset();

        $content = "<?php\n\n";
        if ($namespace) {
            $content .= "namespace " . trim($namespace, '\\') . ";\n\n";
        }

        $content .= <<<PHP
/**
 * Database constants for schema '{$this->schema->getDatabaseName()}'
 * @schema-hash md5:{$schemaHash}
 * @generated   {date('Y-m-d H:i:s')}
 * @tool       tbl-class v3
 * ⚠ AUTO-GENERATED - DO NOT EDIT MANUALLY
 */
class Tbl
{

PHP;

        // Constantes de tabelas + colunas
        foreach ($tables as $table) {
            $content .= $this->generateTableSection($table, $aliases);
        }

        // Table aliases
        if (!empty($aliases)) {
            $content .= "\n    // ==================== Table Aliases ====================\n\n";
            foreach ($aliases as $a) {
                $content .= "    $a";
            }
        }

        // Foreign Keys
        if (!empty($foreignKeys)) {
            $content .= "\n    // ==================== Foreign Keys ====================\n\n";
            foreach ($foreignKeys as $fk) {
                $content .= $this->generateForeignKeyLine($fk);
            }

            // on_* constants se houver FK
            $content .= $this->generateOnConstants($foreignKeys);
        }

        $content .= "}\n\n";
        $content .= "# auto-generated by tbl-class v3.2 CLI\n";
        $content .= "# php vendor/bin/tbl-class          # ↻ regenerate\n";
        $content .= "# php vendor/bin/tbl-class --check  # ✓ check\n";

        return $content;
    }

    /**
     * Seção de tabela + colunas + aliases
     */
    protected function generateTableSection(string $table, array &$aliases = []): string
    {
        $columns = $this->schema->getColumns($table);
        if (empty($columns)) return '';

        $alias = $this->namingResolver->getTableAlias($table);

        $tableConst = $this->namingResolver->getTableConstName($table, $this->mode);

        $output = "\n    /** table: $table (alias: $alias) */\n";
        $output .= "    public const $tableConst = '$table';\n";

        foreach ($columns as $column) {
            $columnConst = $this->namingResolver->getColumnConstName($table, $column);
            $output .= "    /** `$table`.`$column` */ public const $columnConst = '$column';\n";
        }

        // Alias
        $aliases[] = "    /** alias: `$alias` */ public const as_{$tableConst} = '$table $alias';\n";

        return $output;
    }

    /**
     * Linha de foreign key
     */
    protected function generateForeignKeyLine(array $fk): string
    {
        $fkConst = $this->namingResolver->getForeignKeyConstName(
            $fk['from_table'],
            $fk['to_table'],
            $this->mode
        );

        $comment = "    " . $this->namingResolver->getForeignKeyComment($fk);
        $line = "    public const $fkConst = '{$fk['from_column']}';\n";

        return $comment . $line;
    }
}
