<?php


namespace Eril\TblClass\Generators;

use Eril\TblClass\Config;
use PDO;

class TableClassesGenerator extends Generator
{
    public function __construct(PDO $pdo, Config $config, bool $checkMode = false)
    {
        parent::__construct($pdo, $config, $checkMode, 'schema');
        $this->mode = 'schema';
    }

    protected function generateContent(
        array $tables,
        array $foreignKeys = [],
        ?string $schemaHash = null
    ): string {
        $content  = "<?php\n\n";
        $content .= $this->generateHeader($schemaHash);
        $content .= $this->generateTblClass($tables);
        $content .= $this->generateTableClasses($tables, $foreignKeys);
        $content .= "\n// auto-generated by tbl-class v3\n";

        return $content;
    }

    private function generateHeader(string $schemaHash): string
    {
        $time = date('Y-m-d H:i:s');
        return <<<PHP
/**
 * Database schema classes
 *
 * @schema-hash md5:$schemaHash
 * @generated   $time
 * @tool        tbl-class
 *
 * ⚠ AUTO-GENERATED - DO NOT EDIT
 */

PHP;
    }

    private function generateTblClass(array $tables): string
    {
        $content = "class Tbl\n{\n";
        $aliases = [];

        foreach ($tables as $table) {
            $const = $this->namingResolver->getTableConstName($table, $this->mode);
            $aliases[] = "public const as_$const = '$table';";
        }
        
        $content .= "\n    // ALIAS \n\n";

        foreach ($aliases as $alias) {
            $content .= "    $alias;\n";
        }

        return $content . "}\n\n";
    }

    private function generateTableClasses(array $tables, array $foreignKeys): string
    {
        $content = '';

        foreach ($tables as $table) {

            // Nome da classe: Tbl + StudlyCase(table_name)
            $className = 'Tbl' . $this->tableClassName($table);

            $columns = $this->getColumns($table);
            $enums   = $this->getEnumConstants($table, false);

            // Filtrar FKs da tabela atual
            $fks = array_filter($foreignKeys, fn($fk) => $fk['from_table'] === $table);

            $content .= "class {$className}\n{\n";

            // Columns
            foreach ($columns as $column) {
                $name = $this->namingResolver->getColumnConstName(null, $column, $this->mode);
                $content .= "    public const {$name} = '{$column}';\n";
            }

            // ENUMs
            if (!empty($enums)) {
                $content .= "\n    // ENUM values\n";
                foreach ($enums as $name => $value) {
                    $content .= "    public const enum_{$name} = '{$value}';\n";
                }
            }

            // Foreign Keys
            if (!empty($fks)) {
                $content .= "\n    // Foreign Keys\n";
                foreach ($fks as $fk) {
                    $fkName = $this->namingResolver->getForeignKeyConstName(
                        null,
                        $fk['to_table'],
                        $this->mode,
                        false
                    );
                    $content .= "    public const {$fkName} = '{$fk['from_column']}';\n";
                }
            }

            $content .= "\n    public const _TABLE = '{$table}';\n";
            $content .= "\n    public const _ALIAS = '{$this->namingResolver->getTableAlias($table)}';\n";
            $content .= "}\n\n";
        }

        return $content;
    }

    private function tableCLassName(string $table)
    {
        $tableName = $this->namingResolver->getTableConstName($table, $this->mode);
        return str_replace(
            ' ',
            '',
            ucwords(str_replace('_', ' ', $tableName))
        );
    }
}
