<?php
// src/GlobalGenerator.php

namespace Eril\TblClass;

use PDO;
use Exception;

class GlobalGenerator extends Generator
{
    private array $foreignKeys = [];

    public function __construct(PDO $pdo, Config $config, bool $checkMode = false)
    {
        parent::__construct($pdo, $config, $checkMode, 'global');
        $this->mode = 'global';
    }

    protected function generateContent(array $tables, array $foreignKeys = []): string
    {
        $content = "<?php\n\n";
        $content .= $this->generateHeader();
        $content .= $this->generateGlobalConstants($tables);
        $content .= "\n" . $this->generateForeignKeyConstants($foreignKeys);

        return $content;
    }

    private function generateHeader(): string
    {
        $header = "/**\n";
        $header .= " ** Database constants\n";
        $header .= " *  Schema: {$this->dbName}\n";
        $header .= " *  Date: " . date('Y-m-d H:i:s') . "\n";
        $header .= " *! Auto Generated file - DO NOT EDIT THIS FILE MANUALLY\n";
        $header .= " */\n\n";

        return $header;
    }

    private function generateGlobalConstants(array $tables): string
    {
        $content = '';

        foreach ($tables as $table) {
            $columns = $this->getColumns($table);

            if (empty($columns)) {
                continue;
            }

            $tableConst = 'tbl_' . strtolower($table);
            $content .= "// --- Table: $table ---\n";
            $content .= "const {$tableConst} = '$table';\n";

            foreach ($columns as $column) {
                $constName = $tableConst . '_' . strtolower($column);
                $content .= "const {$constName} = '$column';\n";
            }

            $content .= "\n";
        }

        return $content;
    }

    private function generateForeignKeyConstants(array $foreignKeys): string
    {
        $content = '';

        if (empty($foreignKeys)) {
            $content .= "// No foreign keys found in the database\n";
            return $content;
        }

        $content .= "// --- Foreign Keys ---\n\n";
        foreach ($foreignKeys as $fk) {
            $constName = 'tbl_fk_' . strtolower($fk['from_table']) . '_' . strtolower($fk['to_table']);
            $value = $fk['from_column'];

            $content .= "/** Foreign key: {$fk['from_table']}.{$fk['from_column']} → {$fk['to_table']}.{$fk['to_column']} */\n";
            $content .= "const {$constName} = '{$value}';\n";
        }

        return $content;
    }

    protected function showInstructions(): void
    {
        $outputFile = $this->config->getOutputFile($this->mode);
        $relativePath = str_replace(getcwd() . '/', '', $outputFile);

        echo "\n💡 To use these constants, add to composer.json:\n";
        echo "   \"autoload\": {\n";
        echo "       \"files\": [\"$relativePath\"]\n";
        echo "   }\n";
        echo "\n   Then run: composer dump-autoload\n";
        echo str_repeat('-', 50) . "\n";
    }
}