<?php
// src/TableClassGenerator.php

namespace Eril\TblClass;

class TableClassGenerator extends Generator
{

    protected function generateContent(array $tables, array $foreignKeys = []): string
    {
        $namespace = $this->config->get('output.namespace');

        $content = "<?php\n\n";

        if ($namespace) {
            $content .= "namespace " . trim($namespace, '\\') . ";\n\n";
        }
        
        $content .= "/**\n";
        $content .= " * Database table constants Helper\n";
        $content .= " * @source schema {$this->dbName}\n";
        $content .= " * @since " . date('Y-m-d H:i:s') . "\n";
        $content .= " * @auto-generated DO NOT EDIT THIS FILE MANUALLY\n";
        $content .= " */\n";
        $content .= "class " . self::CLASS_NAME . "\n{\n";

        foreach ($tables as $table) {
            $columns = $this->getColumns($table);

            if (empty($columns)) {
                continue;
            }

            $prefix = strtolower($table);
            $content .= "\n    // Table: $table\n";
            $content .= "    public const $prefix = '$table';\n";

            foreach ($columns as $column) {
                $const = $prefix . '_' . strtolower($column);
                $content .= "    public const $const = '$column';\n";
            }
        }

        // SEMPRE incluir FKs se existirem
        if (!empty($foreignKeys)) {
            $content .= "\n    // --- Foreign Keys ---\n";

            foreach ($foreignKeys as $fk) {
                $constName = 'fk_' . strtolower($fk['from_table']) . '_' . strtolower($fk['to_table']);
                $comment   = "    /** {$fk['from_table']}.{$fk['from_column']} → {$fk['to_table']}.{$fk['to_column']} */\n";
                $const     = "    public const $constName = '{$fk['from_column']}';\n";

                $content .= $comment . $const;
            }
        }

        $content .= "}\n";
        return $content;
    }
}
