<?php

namespace Eril\TblClass;

use Eril\TblClass\Traits\OnJoinGenerator;

class TableClassGenerator extends Generator
{

    use OnJoinGenerator;

    protected function generateContent(array $tables, array $foreignKeys = []): string
    {
        $namespace = $this->config->get('output.namespace');
        $aliases = [];
        $this->namingResolver->reset();

        $content = "<?php\n\n";
        if ($namespace) {
            $content .= "namespace " . trim($namespace, '\\') . ";\n\n";
        }

        $content .= "/**\n";
        $content .= " * Database constants for schema '{$this->dbName}'\n";
        $content .= " * @generated " . date('Y-m-d H:i:s') . "\n";
        $content .= " * @tool tbl-class\n";
        $content .= " * @warning AUTO-GENERATED - DO NOT EDIT MANUALLY\n";
        $content .= " */\n";
        $content .= "class " . self::CLASS_NAME . "\n{\n";

        // Constantes de tabelas (cada tabela agrupada)
        foreach ($tables as $table) {
            $content .= $this->generateTableSection($table, $aliases);
        }

        // Table Aliases
        if (!empty($aliases)) {
            $content .= "\n\n\n    //  ==================== Table Alias ====================\n\n";
            foreach ($aliases as $a) {
                $content .= "    $a";
            }

            $tbl = $this->namingResolver->getTableConstName($table, $this->mode, 'abbr');
            $content .= "    public const as_{$tbl} = '$table $tbl';\n";
        }

        // Constantes FK
        if (!empty($foreignKeys)) {
            $content .= "\n\n\n    // ==================== Foreign Keys ====================\n\n";
            foreach ($foreignKeys as $fk) {
                $content .= $this->generateForeignKeyLine($fk);
            }
        }

        // Métodos on_ (opcional - configurável)
        if (!empty($foreignKeys)) {
            $content .= $this->generateOnConstants($foreignKeys);
        }

        $content .= "}\n";

        $content .= "\n# auto-generated by tbl-class v3.1 CLI:";
        $content .= "\n# php vendor/bin/tbl-class          # ↻ regenerate";
        $content .= "\n# php vendor/bin/tbl-class --check  # ✓ check\n";

        return $content;
    }

    protected function generateTableSection(string $table, &$aliases = []): string
    {
        $columns = $this->getColumns($table);
        if (empty($columns)) return '';

        $alias = $this->namingResolver->getTableAlias($table);

        $output = "\n    /** table: $table (alias: $alias)*/\n";

        // Table constant
        $tableConst = $this->namingResolver->getTableConstName($table, $this->mode);
        $output .= "    public const $tableConst = '$table';\n";

        // Columns
        foreach ($columns as $column) {
            $columnConst = $this->namingResolver->getColumnConstName($table, $column, $this->mode);
            $output .= "    /** `$table`.`$column` */ \tpublic const $columnConst = '$column';\n";
        }

        // Alias (se necessário)
        $doc = "/** alias: `$table` → `$alias`  */";
        $aliases[] = "$doc public const as_{$tableConst} = '$table $alias';\n";
        return $output;
    }

    protected function generateForeignKeyLine(array $fk): string
    {
        $fkConst = $this->namingResolver->getForeignKeyConstName(
            $fk['from_table'],
            $fk['to_table'],
            $this->mode
        );

        $comment = "    " . $this->namingResolver->getForeignKeyComment($fk);
        $line = "    public const $fkConst = '{$fk['from_column']}';\n";

        return $comment . $line;
    }
}
