<?php
// src/TableClassGenerator.php

namespace Eril\TblClass;

class TableClassGenerator extends Generator
{
    protected function generateContent(array $tables, array $foreignKeys = []): string
    {
        $namespace = $this->config->get('output.namespace');


        // Reset used names para evitar duplicatas
        $this->namingResolver->reset();

        $content = "<?php\n\n";

        if ($namespace) {
            $content .= "namespace " . trim($namespace, '\\') . ";\n\n";
        }

        $content .= "/**\n";
        $content .= " * Database constants for schema '{$this->dbName}'\n";
        $content .= " * \n";
        $content .= " * @generated " . date('Y-m-d H:i:s') . "\n";
        $content .= " * @tool      tbl-class\n";
        $content .= " * \n";
        $content .= " * @warning AUTO-GENERATED - DO NOT EDIT MANUALLY\n";
        $content .= " */\n";
        $content .= "class " . self::CLASS_NAME . "\n{\n";

        foreach ($tables as $table) {
            $columns = $this->getColumns($table);

            if (empty($columns)) {
                continue;
            }

            // CORREÇÃO AQUI: Usa NamingResolver para obter o nome da constante da tabela
            $tableConst = $this->namingResolver->getTableConstName($table, $this->mode);
            $content .= "\n    /** Table: $table */\n";
            $content .= "    public const $tableConst = '$table';\n";

            foreach ($columns as $column) {
                $columnConst = $this->namingResolver->getColumnConstName($table, $column, $this->mode);
                $content .= "    public const $columnConst = '$column';\n";
            }
        }

        // SEMPRE incluir FKs se existirem
        if (!empty($foreignKeys)) {
            $content .= "\n    // --- Foreign Keys ---\n\n";

            foreach ($foreignKeys as $fk) {
                // CORREÇÃO AQUI: Usa NamingResolver para obter o nome da constante FK
                $fkConst = $this->namingResolver->getForeignKeyConstName(
                    $fk['from_table'],
                    $fk['to_table'],
                    $this->mode
                );
                $comment = "    " . $this->namingResolver->getForeignKeyComment($fk);
                $const   = "    public const $fkConst = '{$fk['from_column']}';\n";

                $content .= $comment . $const;
            }
        }

        $content .= "}\n";

        // copyright
        $content .= "\n# auto-generated by tbl-class v3.1 CLI";
        $content .= "\n# ↻ php vendor/bin/tbl-class          # regenerate";
        $content .= "\n# ✓ php vendor/bin/tbl-class --check  # check\n";

        return $content;
    }
}
